apiVersion: v1
kind: Pod
metadata:
  name: gb-frontend
  namespace: lab
  labels:
    app: gb-frontend
spec:
  containers:
  - name: gb-frontend
    image: gcr.io/google-samples/gb-frontend-amd64:v5
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
