apiVersion: v1
kind: Service
metadata:
  name: gb-frontend-svc
  namespace: lab
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: gb-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
