apiVersion: apps/v1
kind: Deployment
metadata:
  name: gb-frontend
  namespace: lab
  labels:
    run: gb-frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      run: gb-frontend
  template:
    metadata:
      labels:
        run: gb-frontend
        app: gb-frontend
    spec:
      containers:
      - name: gb-frontend
        image: gcr.io/google-samples/gb-frontend-amd64:v5
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
