apiVersion: v1
kind: Pod
metadata:
  name: liveness-demo-pod
  namespace: lab
  labels:
    demo: liveness-probe
spec:
  containers:
  - name: liveness-demo-pod
    image: quay.io/centos/centos:stream9
    args: ["/bin/sh","-c","touch /tmp/alive; sleep infinity"]
    livenessProbe:
      exec:
        command: ["cat","/tmp/alive"]
      initialDelaySeconds: 5
      periodSeconds: 10
