apiVersion: v1
kind: Pod
metadata:
  name: readiness-demo-pod
  namespace: lab
  labels:
    demo: readiness-probe
spec:
  containers:
  - name: readiness-demo-pod
    image: nginx
    ports:
    - containerPort: 80
    readinessProbe:
      exec:
        command: ["cat","/tmp/healthz"]
      initialDelaySeconds: 5
      periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: readiness-demo-svc
  namespace: lab
  labels:
    demo: readiness-probe
spec:
  type: LoadBalancer
  selector:
    demo: readiness-probe
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
